# Cloudflare Pages configuration
name = "blog"
compatibility_date = "2024-11-11"
account_id = "0069347c7b5b737a5a9a944a79ed5c2e"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "c3ab4871-fc47-4bc2-b0ed-c808d567d118" # You'll get this after creating the D1 database
